runtime: python27
api_version: 1
threadsafe: yes
service: backend

handlers:
- url: /(.*)
  script: main.app
#  http_headers:
#    Access-Control-Allow-Origin: "*"

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest

builtins:
- deferred: on

skip_files:
- node_modules

env_variables:
  FIREBASE_PROJECT_ID: 'chitchat-157309
'
